MSGID_JIUYINZHI_OPEN = 1
MSGID_JIUYINZHI_GET_EVENT = 2
MSGID_JIUYINZHI_GET_EVENT_DETAIL = 3
MSGID_JIUYINZHI_QUERY_HIGH_LIGHT = 4
MSGID_JIUYINZHI_UPDATE_VIEW_GAME_STEP = 5
MSGID_JIUYINZHI_QUERY_CURRENT_GAME_STEP = 6
MSGID_JIUYINZHI_GET_AWARD_EVENT = 7
