FRIEND_REC = "rec_friend"
BUDDY_REC = "rec_buddy"
BROTHER_REC = "rec_brother"
ENEMY_REC = "rec_enemy"
BLOOD_REC = "rec_blood"
FILTER_REC = "rec_filter"
ATTENTION_REC = "rec_attention"
FANS_REC = "rec_fans"
PRESENT_REC = "rec_present"
QIFU_REC = "rec_qifu"
JIESHI_REC = "rec_acquaint"
TEACHER_PUPIL_REC = "rec_teacherpupil"
PUPIL_JINGMAI_REC = "rec_jingmai_tp"
SWORN_REC = "SwornRelationRec"
FRIEND_REC_UID = 0
FRIEND_REC_NAME = 1
FRIEND_REC_PHOTO = 2
FRIEND_REC_CHENGHAO = 3
FRIEND_REC_LEVEL = 4
FRIEND_REC_MENPAI = 5
FRIEND_REC_BANGPAI = 6
FRIEND_REC_XINQING = 7
FRIEND_REC_ONLINE = 8
FRIEND_REC_SCENE = 9
FRIEND_REC_MODEL = 10
ENEMY_REC_UID = 0
ENEMY_REC_NAME = 1
ENEMY_REC_PHOTO = 2
ENEMY_REC_CHENGHAO = 3
ENEMY_REC_LEVEL = 4
ENEMY_REC_MENPAI = 5
ENEMY_REC_BANGPAI = 6
ENEMY_REC_XINQING = 7
ENEMY_REC_ONLINE = 8
ENEMY_REC_SCENE = 9
ENEMY_REC_MODEL = 10
ACQUAINT_REC_UID = 0
ACQUAINT_REC_NAME = 1
ACQUAINT_REC_PHOTO = 2
ACQUAINT_REC_CHENGHAO = 3
ACQUAINT_REC_LEVEL = 4
ACQUAINT_REC_MENPAI = 5
ACQUAINT_REC_BANGPAI = 6
ACQUAINT_REC_XINQING = 7
ACQUAINT_REC_ONLINE = 8
ACQUAINT_REC_SCENE = 9
ACQUAINT_REC_MODEL = 10
ACQUAINT_REC_GOOD = 11
ACQUAINT_REC_BAD = 12
ACQUAINT_COUNT = 13
ACQUAINT_LASTTIME = 14
ACQUAINT_THING1 = 15
ACQUAINT_THING2 = 16
ACQUAINT_THING3 = 17
ACQUAINT_THINGDETAIL1 = 18
ACQUAINT_THINGDETAIL2 = 19
ACQUAINT_THINGDETAIL3 = 20
FANS_REC_UID = 0
FANS_REC_NAME = 1
FANS_REC_PHOTO = 2
FANS_REC_CHENGHAO = 3
FANS_REC_LEVEL = 4
FANS_REC_MENPAI = 5
FANS_REC_BANGPAI = 6
FANS_REC_XINQING = 7
FILTER_REC_UID = 0
FILTER_REC_NAME = 1
FILTER_REC_PHOTO = 2
PUPIL_REC_NAME = 0
PUPIL_REC_TYPE = 1
PUPIL_REC_LEVEL = 2
PUPIL_REC_DATE_BAISHI = 3
PUPIL_REC_RECENT_ONLINE = 4
PUPIL_REC_SHI_TU_VALUE = 5
PUPIL_REC_OLSTATE = 6
PUPIL_REC_GUILD = 7
PUPIL_REC_SEX = 12
PUPIL_REC_UID = 14
PUPIL_REC_MODEL = 17
PUPIL_REC_ROLE_PHOTO = 18
PUPIL_REC_JM_UID = 0
PUPIL_REC_JM_NAME = 1
PUPIL_REC_JM_GUILD = 2
PUPIL_REC_JM_SEX = 3
PUPIL_REC_JM_ROLE_INFO = 4
PUPIL_REC_JM_ROLE_MODEL = 5
PUPIL_REC_JM_TYPE = 6
PUPIL_REC_M_BAISHI_DATE = 7
PUPIL_REC_JM_RECENT_ONLINE_DATE = 8
PUPIL_REC_JM_ACTIVE_TYPE = 9
PUPIL_REC_JM_OLSTATE = 10
PUPIL_REC_JM_XUEWEI_COUNT = 11
PUPIL_REC_JM_SHI_TU_VALUE = 12
PUPIL_REC_JM_ROLE_PHOTO = 14
local SWORN_REC_COL_NAME = 0
local SWORN_REC_COL_ONLINE = 1
FRIEND_TYPE = 1
BUDDY_TYPE = 2
BROTHER_TYPE = 3
ENEMY_TYPE = 4
BLOOD_TYPE = 5
FILTER_TYPE = 6
GUANZHU_TYPE = 7
JIESHI_TYPE = 8
BLACK_TYPE = 9
RELATION_GROUP_ZONGLAN = 0
RELATION_GROUP_RENMAI = 1
RELATION_GROUP_SHILI = 2
RELATION_GROUP_SELF = 3
RELATION_SUB_GROUP_FRIEND = 8
RELATION_SUB_GROUP_ENEMY = 9
RELATION_SUB_GROUP_ATTENTION = 10
RELATION_SUB_GROUP_RENMAI_SELF = 11
RELATION_SUB_GROUP_TEACHER_PUPIL = 15
RELATION_SUB_GROUP_NPC_FRIEND = 16
RELATION_SUB_GROUP_NPC_BUDDY = 17
RELATION_SUB_GROUP_NPC_ATTENTION = 18
RELATION_GPOUP_WORLD = 39
RELATION_SUB_GROUP_09 = 70
RELATION_SUB_GROUP_10 = 71
RELATION_SUB_GROUP_11 = 72
RELATION_SUB_GROUP_12 = 73
RELATION_SUB_GROUP_13 = 74
RELATION_SUB_GROUP_14 = 75
RELATION_SUB_GROUP_15 = 76
RELATION_SUB_GROUP_16 = 77
RELATION_SUB_GROUP_17 = 78
RELATION_SUB_GROUP_18 = 79
str_group = {
  "zonglan",
  "renmai",
  "shili",
  "self",
  "world"
}
RELATION_TYPE_RENMAI = 0
RELATION_TYPE_SHILI = 1
RELATION_TYPE_SELF = 2
RELATION_TYPE_WORLD = 3
RELATION_TYPE_ZONGLAN_MAX = 4
RELATION_TYPE_RENMAI_SELF = 0
RELATION_TYPE_FRIEND = 1
RELATION_TYPE_BUDDY = 2
RELATION_TYPE_ENEMY = 3
RELATION_TYPE_BLOOD = 4
RELATION_TYPE_ATTENTION = 5
RELATION_TYPE_TEACHER_PUPIL = 6
RELATION_TYPE_NPC_FRIEND = 7
RELATION_TYPE_NPC_BUDDY = 8
RELATION_TYPE_NPC_ATTENTION = 9
RELATION_TYPE_RENMAI_MAX = 11
RELATION_TYPE_BROTHER = 50
RELATION_TYPE_FANS = 51
RELATION_TYPE_WORLD_A = 0
SnsManagerCacheName = "sns_manager_cache"
MaxCharacterValue = 7200
SHILI_MIN = 1
SHILI_MAX = 200
JINDI_MIN = 201
JINDI_MAX = 300
function get_karma_msg_config(value, grouped)
  local ini = nx_execute("util_functions", "get_ini", "share\\sns\\msg_config.ini")
  if not nx_is_valid(ini) then
    return
  end
  value = nx_int(value)
  local sec_index = -1
  if grouped then
    sec_index = ini:FindSectionIndex("GroupKarma")
  else
    sec_index = ini:FindSectionIndex("Karma")
  end
  if sec_index < 0 then
    return
  end
  local min_value = 0
  local max_value = 0
  local name, pic
  local GroupMsgData = ini:GetItemValueList(sec_index, nx_string("r"))
  for i = 1, nx_number(table.getn(GroupMsgData)) do
    local stepData = util_split_string(GroupMsgData[i], ",")
    if nx_int(min_value) > nx_int(stepData[1]) then
      min_value = nx_int(stepData[1])
    end
    if nx_int(max_value) < nx_int(stepData[2]) then
      max_value = nx_int(stepData[2])
    end
    if value >= nx_int(stepData[1]) and value <= nx_int(stepData[2]) then
      name = nx_string(stepData[3])
      pic = nx_string(stepData[4])
    end
  end
  return min_value, max_value, name, pic
end
