local CLIENT_SUBMSG_REQUEST_JOIN_RANDOM_CLONE = 0
local CLIENT_SUBMSG_CANCEL_WATI_RANDOM_CLONE = 1
local CLIENT_SUBMSG_CAPTAIN_REQUEST_RANDOM_CLONE = 2
local CLIENT_SUBMSG_REQUEST_ENTER_CLONE = 4
local CLIENT_SUBMSG_REQUEST_OUT_CLONE = 5
local MAX_RESET_COUNT = 7
local CLONE_SAVE_REC = "clone_rec_save"
