CHATTYPE_SILENCE = 0
CHATTYPE_VISUALRANGE = 1
CHATTYPE_SCENE = 2
CHATTYPE_WHISPER = 3
CHATTYPE_TEAM = 4
CHATTYPE_FRIEND = 5
CHATTYPE_GUILD = 6
CHATTYPE_UNION = 7
CHATTYPE_SCHOOL = 8
CHATTYPE_WORLD = 9
CHATTYPE_GOSSIP = 10
CHATTYPE_SMALL_SPEAKER = 12
CHATINFO_OFFLINE = 13
CHATTYPE_MOVIE = 14
CHATINFO_BOSS = 15
CHATTYPE_TALKBYID = 16
CHATTYPE_SYSTEM = 17
CHATTYPE_ROW = 19
CHATTYPE_GETSILVER_CARD = 20
CHATTYPE_DECSILVER_CARD = 21
CHATTYPE_SCHOOL_FIGHT = 22
CHATTYPE_BATTLE_FIELD = 23
CHATTYPE_DEAL = 24
CHATTYPE_WORLD_WAR = 25
CHATTYPE_GET_SPEAKER_RANK = 26
CHATTYPE_GET_SPEAKER_QUEUE = 27
CHATTYPE_MARRY = 28
CHATTYPE_FORCE = 30
CHATTYPE_NEW_SCHOOL = 32
CHATTYPE_NEW_TERRITORY = 33
CHATTYPE_OUTLAND_WAR = 34
CHATTYPE_MATCH_SANMENG = 35
CHATTYPE_CROSS_SMALL_SPEAKER = 36
CHATTYPE_SHOW_HIDE_CROSS_SPEAKER = 37
CHATTYPE_SANMENG_INTEGRAL = 38
CHATTYPE_ALL_SCHOOL = 39
CHATTYPE_GUILD_LEAGUE = 40
CHATTYPE_BALANCE_WAR = 41
CHATTYPE_WUDAO = 42
CHATTYPE_LUANDOU = 43
CHATTYPE_NEW_WAR_RULE_START = 80
CHATTYPE_NEW_WAR_RULE_END = 90
CHATTYPE_WHISPER_ECHO = 103
CHATTYPE_FRIEND_ECHO = 105
CHATTYPE_MAX = 256
chat_zonghe_set = {
  CHATTYPE_VISUALRANGE,
  CHATTYPE_SCENE,
  CHATTYPE_TEAM,
  CHATTYPE_GUILD,
  CHATTYPE_SCHOOL,
  CHATTYPE_WORLD,
  CHATTYPE_GOSSIP,
  CHATTYPE_ROW,
  CHATTYPE_NEW_WAR_RULE_START,
  CHATTYPE_BATTLE_FIELD,
  CHATTYPE_DEAL,
  CHATTYPE_WORLD_WAR,
  CHATTYPE_FORCE,
  CHATTYPE_NEW_SCHOOL,
  CHATTYPE_NEW_TERRITORY,
  CHATTYPE_OUTLAND_WAR,
  CHATTYPE_MATCH_SANMENG,
  CHATTYPE_ALL_SCHOOL,
  CHATTYPE_GUILD_LEAGUE,
  CHATTYPE_BALANCE_WAR,
  CHATTYPE_WUDAO,
  CHATTYPE_LUANDOU
}
