CLIENT_CUSTOMMSG_WORLD_WAR = 995
CLIENT_WORLDWAR_SIGNUP = 0
CLIENT_WORLDWAR_SIGNUP_QUIT = 1
CLIENT_WORLDWAR_EXIT = 2
CLIENT_WORLDWAR_REQUEST_SIGNUP_INFO = 3
CLIENT_WORLDWAR_STAT_INFO = 4
CLIENT_WORLDWAR_INFO = 5
CLIENT_WORLDWAR_ARMY = 6
CLIENT_WORLDWAR_STATE_INFO = 7
CLIENT_WORLDWAR_STATION_INFO = 8
CLIENT_WORLDWAR_WUJIANG_INFO = 9
CLIENT_WORLDWAR_ESCORT_CONTROL = 10
CLIENT_WORLDWAR_LEAVE = 11
CLIENT_WORLDWAR_ADVANCE_SIGNUP = 12
CLIENT_WORLDWAR_ADVANCE_SIGNUP_QUIT = 13
CLIENT_WORLDWAR_TRAITOR_VOTE_INFO = 14
CLIENT_WORLDWAR_TRAITOR_VOTE = 15
CLINET_WORLDWAR_TRAITOR_VOTE_CANCEL = 16
CLINET_WORLDWAR_JOIN_HERO_CURE = 17
CLINET_WORLDWAR_HERO_INFO = 18
CLIENT_WORLDWAR_TRAITOR_BETRAY = 19
CLIENT_WORLDWAR_TRAITOR_INFO = 20
CLIENT_WORLDWAR_STAT_INFO2 = 21
CLIENT_WORLDWAR_STAT_INFO_REQ = 22
CLIENT_WORLDWAR_TREASURE_TALLY = 23
CLIENT_WORLDWAR_TRAITOR_ITEM = 24
CLIENT_WORLDWAR_GENERAL_INFO = 26
world_war_table = {400, 401}
sub_game_table = {
  ["400"] = {
    "sub_game_400_1",
    "sub_game_400_2"
  },
  ["401"] = {
    "sub_game_401_1",
    "sub_game_401_2",
    "sub_game_401_1"
  }
}
